uint64 error_count
float32 x		# angular velocity in the NED X board axis in rad/s
float32 y		# angular velocity in the NED Y board axis in rad/s
float32 z		# angular velocity in the NED Z board axis in rad/s
float32 temperature	# temperature in degrees celsius

int16 x_raw
int16 y_raw
int16 z_raw
int16 temperature_raw

uint32 device_id	# unique device ID for the sensor that does not change between power cycles
