uint64 integral_dt	# integration time
uint64 error_count
float32 x_integral	# delta angle in the NED X board axis in radians in the integration time frame
float32 y_integral	# delta angle in the NED Y board axis in radians in the integration time frame
float32 z_integral	# delta angle in the NED Z board axis in radians in the integration time frame

uint32 device_id	# unique device ID for the sensor that does not change between power cycles
